/*
 * Applications.
 */

// Fetch.
export const FETCH_APPLICATIONS = 'FETCH_APPLICATIONS';
export const FETCH_APPLICATIONS_PENDING = 'FETCH_APPLICATIONS_PENDING';
export const FETCH_APPLICATIONS_REJECTED = 'FETCH_APPLICATIONS_REJECTED';
export const FETCH_APPLICATIONS_FULFILLED = 'FETCH_APPLICATIONS_FULFILLED';

export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUPS_PENDING = 'FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_REJECTED = 'FETCH_GROUPS_REJECTED';
export const FETCH_GROUPS_FULFILLED = 'FETCH_GROUPS_FULFILLED';

export const FETCH_CLIENTS = 'FETCH_CLIENTS';
export const FETCH_CLIENTS_PENDING = 'FETCH_CLIENTS_PENDING';
export const FETCH_CLIENTS_REJECTED = 'FETCH_CLIENTS_REJECTED';
export const FETCH_CLIENTS_FULFILLED = 'FETCH_CLIENTS_FULFILLED';

// Fetch single.
export const FETCH_APPLICATION = 'FETCH_APPLICATION';
export const FETCH_APPLICATION_PENDING = 'FETCH_APPLICATION_PENDING';
export const FETCH_APPLICATION_REJECTED = 'FETCH_APPLICATION_REJECTED';
export const FETCH_APPLICATION_FULFILLED = 'FETCH_APPLICATION_FULFILLED';

export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const UPDATE_APPLICATION_PENDING = 'UPDATE_APPLICATION_PENDING';
export const UPDATE_APPLICATION_REJECTED = 'UPDATE_APPLICATION_REJECTED';
export const UPDATE_APPLICATION_FULFILLED = 'UPDATE_APPLICATION_FULFILLED';
export const CANCEL_APPLICATION_CHANGE = 'CANCEL_APPLICATION_CHANGE';

// Fetch status.
export const FETCH_STATUS = 'FETCH_STATUS';
export const FETCH_STATUS_PENDING = 'FETCH_STATUS_PENDING';
export const FETCH_STATUS_REJECTED = 'FETCH_STATUS_REJECTED';
export const FETCH_STATUS_FULFILLED = 'FETCH_STATUS_FULFILLED';

// Fetch authz status.
export const FETCH_AUTHORIZATION_STATUS = 'FETCH_AUTHORIZATION_STATUS';
export const FETCH_AUTHORIZATION_STATUS_PENDING = 'FETCH_AUTHORIZATION_STATUS_PENDING';
export const FETCH_AUTHORIZATION_STATUS_REJECTED = 'FETCH_AUTHORIZATION_STATUS_REJECTED';
export const FETCH_AUTHORIZATION_STATUS_FULFILLED = 'FETCH_AUTHORIZATION_STATUS_FULFILLED';

// Fetch update authz.
export const UPDATE_AUTHORIZATION_STATUS = 'UPDATE_AUTHORIZATION_STATUS';
export const UPDATE_AUTHORIZATION_STATUS_PENDING = 'UPDATE_AUTHORIZATION_STATUS_PENDING';
export const UPDATE_AUTHORIZATION_STATUS_REJECTED = 'UPDATE_AUTHORIZATION_STATUS_REJECTED';
export const UPDATE_AUTHORIZATION_STATUS_FULFILLED = 'UPDATE_AUTHORIZATION_STATUS_FULFILLED';

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const CHECK_STATUS = 'CHECK_STATUS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Fetch.
export const FETCH_CONNECTIONS = 'FETCH_CONNECTIONS';
export const FETCH_CONNECTIONS_PENDING = 'FETCH_CONNECTIONS_PENDING';
export const FETCH_CONNECTIONS_REJECTED = 'FETCH_CONNECTIONS_REJECTED';
export const FETCH_CONNECTIONS_FULFILLED = 'FETCH_CONNECTIONS_FULFILLED';

// Create application
export const REQUEST_APPLICATION_CREATE = 'REQUEST_APPLICATION_CREATE';
export const CANCEL_APPLICATION_CREATE = 'CANCEL_APPLICATION_CREATE';
export const CREATE_APPLICATION = 'CREATE_APPLICATION';
export const CREATE_APPLICATION_PENDING = 'CREATE_APPLICATION_PENDING';
export const CREATE_APPLICATION_REJECTED = 'CREATE_APPLICATION_REJECTED';
export const CREATE_APPLICATION_FULFILLED = 'CREATE_APPLICATION_FULFILLED';

// Move application
export const MOVE_APPLICATION = 'MOVE_APPLICATION';
export const MOVE_APPLICATION_PENDING = 'MOVE_APPLICATION_PENDING';
export const MOVE_APPLICATION_REJECTED = 'MOVE_APPLICATION_REJECTED';
export const MOVE_APPLICATION_FULFILLED = 'MOVE_APPLICATION_FULFILLED';

// Delete application
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
export const DELETE_APPLICATION_PENDING = 'DELETE_APPLICATION_PENDING';
export const DELETE_APPLICATION_REJECTED = 'DELETE_APPLICATION_REJECTED';
export const DELETE_APPLICATION_FULFILLED = 'DELETE_APPLICATION_FULFILLED';
export const REQUEST_APPLICATION_DELETE = 'REQUEST_APPLICATION_DELETE';
export const CANCEL_APPLICATION_DELETE = 'CANCEL_APPLICATION_DELETE';


export const APPLICATION_CLIENT_CHANGE = 'APPLICATION_CLIENT_CHANGE';
export const APPLICATION_TYPE_CHANGE = 'APPLICATION_TYPE_CHANGE';
export const APPLICATION_NAME_CHANGE = 'APPLICATION_NAME_CHANGE';
