name: Release Develop
on: 
  workflow_dispatch:
  push:
        branches:
          - rework_ci
jobs:
  call-cdn-upload:
    uses: ./.github/workflows/cdn-upload.yml
    secrets:
      aws_role: ${{ secrets.awsIAMS3UploadDevRole }}
    with:
      target: "dev"